---
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
#  - name: oraclelinux
#    image: docker.io/oraclelinux:8
#    pre_build_image: true
#  - name: centos8
#    image: quay.io/centos/centos:stream8
#    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
verifier:
  name: ansible
role_name_check: 1
